### ISSUE TITLE
It disables colorful tags plugin in reading mode

### ISSUE THREAD

**Issue by Expsy** [darrenkuro/obsidian-basetag#4]
It disables colorful tags plugin in reading mode.
![resim](https://github.com/darrenkuro/obsidian-basetag/assets/23268427/016f70cd-839f-490a-9baa-d8ceb61882b4)
![resim](https://github.com/darrenkuro/obsidian-basetag/assets/23268427/ee36edf5-525a-4d2d-aa5f-21ec8399b538)
#gum tag should have a red background, but it doesn't and it only happens If I activate basetag plugin.

I'm not sure if it can be solved, or it is this plugin's fault or others. I love both of the plugins; I wish they could work at the same time :')

**Comment by darrenkuro** [comment]
Seems like a new issue; since I don't personally use the colorful tags plugin I'm not too certain about its structure. 
But I changed some node creation tags to comply with its CSS selectors based on the mode it's in. Looks like the issue's been fixed but might break again if something else changes. 

Let me know if everything works well and if there's any other issue.

**Comment by Expsy** [comment]
Alright, thanks a lot for checking it out! I'll be in my home setup in 2 days to test it, I will let you know.

**Comment by Expsy** [comment]
It works without any issues, thanks a lot for that ❤️
